build: update to `rules_nodejs` v4 stable to support latest version
`rules_sass` currently relies on the NodeJS Bazel rules for the
build action worker, and for actually building & testing the rules.

This version is currently outdated and especially the dependency
on the outdated `@bazel/worker` package results in errors when
the Sass rules are used with `rules_nodejs` v4.x. e.g.

```
Error: Expected package major version to equal @build_bazel_rules_nodejs major version
    @bazel/worker - 3.0.0
    @build_bazel_rules_nodejs - 4.0.0-beta.0
  See https://github.com/bazelbuild/rules_nodejs/wiki/Avoiding-version-skew
    at Object.<anonymous> (/home/circleci/.cache/bazel/_bazel_circleci/25aa7b3d5096b7e5114a3cf6c0d4a5bf/external/build_bazel_rules_sass_deps/_/sass/node_modules/@bazel/worker/npm_version_check.js:17:9)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
)
ERROR: Error fetching repository: Traceback (most recent call last):
```